name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Copy all repository files to the "public" folder,
      # excluding directories that should not be deployed.
      - name: Prepare public folder
        run: |
          mkdir public
          # Use rsync to copy files, excluding the public folder, .git, and .github directories
          rsync -av --progress . public --exclude public --exclude '.git*' --exclude '.github'
          # Create a .nojekyll file so GitHub Pages will not process files with Jekyll
          touch public/.nojekyll

      # Upload the "public" folder as the Pages deployment artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
